services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    env_file:
      - ../.env
    volumes:
      - ..:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
